
# Data extracted from kickboxing-trainer-final-v2 (2).jsx

TRANSLATIONS = {
  'fr': {
    'title': 'Entraînement Kickboxing',
    'warmup': 'Échauffement',
    'jumpRope': 'Corde à sauter',
    'strength': 'Musculation',
    'heavyBag': 'Sac de frappe',
    'shadowBoxing': 'Shadow boxing',
    'cooldown': 'Étirement/Récupération',
    'sparring': 'Sparring',
    'start': 'Démarrer',
    'pause': 'Pause',
    'reset': 'Réinitialiser',
    'round': 'Round',
    'rest': 'Repos',
    'prepare': 'Préparation',
    'work': 'Travail',
    'settings': 'Paramètres',
    'addBlock': 'Ajouter un bloc',
    'duration': 'Durée',
    'rounds': 'Rounds',
    'workTime': 'Temps de travail',
    'restTime': 'Temps de repos',
    'volume': 'Volume',
    'selectTechniques': 'Sélectionner les techniques',
    'punches': 'Coups de poing',
    'kicks': 'Coups de pied',
    'knees': 'Coups de genou',
    'elbows': 'Coudes',
    'combos': 'Combos',
    'selectExercises': 'Sélectionner les exercices',
    'reps': 'Répétitions',
    'speedUp': 'Accélérez !',
    'normalPace': 'Rythme normal',
    'edit': 'Modifier',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'duplicate': 'Dupliquer',
    'rename': 'Renommer',
    'language': 'Langue',
    'saveWorkout': 'Sauvegarder l\'entraînement',
    'loadWorkout': 'Charger',
    'workoutName': 'Nom de l\'entraînement',
    'myWorkouts': 'Mes entraînements',
    'presetWorkouts': 'Séances',
    'preset30min': 'Séance 30 minutes',
    'preset60min': 'Séance 1 heure',
    'preset90min': 'Séance 1h30',
    'minutes': 'Minutes',
    'seconds': 'Secondes',
    'frequency': 'Fréquence d\'énonciation',
    'slow': 'Lent (7s)',
    'normal': 'Normal (5s)',
    'fast': 'Rapide (3s)',
    'double': 'Double',
    'triple': 'Triple',
    'skipRound': 'Passer au round suivant',
    'skipBlock': 'Passer au bloc suivant',
    'voiceProfile': 'Voix',
    'trainingComplete': 'Entraînement terminé !',
    'theme': 'Ambiance',
    'sport': 'Sport',
    'exercise': 'Exercice',
    'backToTraining': 'Retour à l\'entraînement',
    'noSavedWorkouts': 'Aucun entraînement sauvegardé',
    'deleteConfirm': 'Supprimer cet entraînement ?',
    'saveCurrentWorkout': 'Sauvegarder cet entraînement',
    'createdOn:': 'Créé le',
    'newName': 'Nouveau nom',
    'selectWorkout': 'Sélectionner un entraînement'
  },
  'en': {
    'title': 'Kickboxing Training',
    'warmup': 'Warm-up',
    'jumpRope': 'Jump rope',
    'strength': 'Strength training',
    'heavyBag': 'Heavy bag',
    'shadowBoxing': 'Shadow boxing',
    'cooldown': 'Cool-down/Stretching',
    'sparring': 'Sparring',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'round': 'Round',
    'rest': 'Rest',
    'prepare': 'Prepare',
    'work': 'Work',
    'settings': 'Settings',
    'addBlock': 'Add block',
    'duration': 'Duration',
    'rounds': 'Rounds',
    'workTime': 'Work time',
    'restTime': 'Rest time',
    'volume': 'Volume',
    'selectTechniques': 'Select techniques',
    'punches': 'Punches',
    'kicks': 'Kicks',
    'knees': 'Knees',
    'elbows': 'Elbows',
    'combos': 'Combos',
    'selectExercises': 'Select exercises',
    'reps': 'Reps',
    'speedUp': 'Speed up!',
    'normalPace': 'Normal pace',
    'edit': 'Edit',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'duplicate': 'Duplicate',
    'rename': 'Rename',
    'language': 'Language',
    'saveWorkout': 'Save workout',
    'loadWorkout': 'Load',
    'workoutName': 'Workout name',
    'myWorkouts': 'My workouts',
    'presetWorkouts': 'Sessions',
    'preset30min': '30-minute session',
    'preset60min': '1-hour session',
    'preset90min': '1h30 session',
    'minutes': 'Minutes',
    'seconds': 'Seconds',
    'frequency': 'Announcement frequency',
    'slow': 'Slow (7s)',
    'normal': 'Normal (5s)',
    'fast': 'Fast (3s)',
    'double': 'Double',
    'triple': 'Triple',
    'skipRound': 'Skip to next round',
    'skipBlock': 'Skip to next block',
    'voiceProfile': 'Voice',
    'trainingComplete': 'Training complete!',
    'theme': 'Atmosphere',
    'sport': 'Sport',
    'exercise': 'Exercise',
    'backToTraining': 'Back to training',
    'noSavedWorkouts': 'No saved workouts',
    'deleteConfirm': 'Delete this workout?',
    'saveCurrentWorkout': 'Save this workout',
    'createdOn:': 'Created on',
    'newName': 'New name',
    'selectWorkout': 'Select a workout'
  },
  'es': {
    'title': 'Entrenamiento de Kickboxing',
    'warmup': 'Calentamiento',
    'jumpRope': 'Saltar la cuerda',
    'strength': 'Musculación',
    'heavyBag': 'Saco de boxeo',
    'shadowBoxing': 'Shadow boxing',
    'cooldown': 'Estiramiento/Recuperación',
    'sparring': 'Sparring',
    'start': 'Iniciar',
    'pause': 'Pausa',
    'reset': 'Reiniciar',
    'round': 'Round',
    'rest': 'Descanso',
    'prepare': 'Preparación',
    'work': 'Trabajo',
    'settings': 'Ajustes',
    'addBlock': 'Añadir bloque',
    'duration': 'Duración',
    'rounds': 'Rounds',
    'workTime': 'Tiempo de trabajo',
    'restTime': 'Tiempo de descanso',
    'volume': 'Volumen',
    'selectTechniques': 'Seleccionar técnicas',
    'punches': 'Puñetazos',
    'kicks': 'Patadas',
    'knees': 'Rodillas',
    'elbows': 'Codos',
    'combos': 'Combos',
    'selectExercises': 'Seleccionar ejercicios',
    'reps': 'Repeticiones',
    'speedUp': '¡Acelera!',
    'normalPace': 'Ritmo normal',
    'edit': 'Editar',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'duplicate': 'Duplicar',
    'rename': 'Renombrar',
    'language': 'Idioma',
    'saveWorkout': 'Guardar entrenamiento',
    'loadWorkout': 'Cargar',
    'workoutName': 'Nombre del entrenamiento',
    'myWorkouts': 'Mis entrenamientos',
    'presetWorkouts': 'Sesiones',
    'preset30min': 'Sesión 30 minutos',
    'preset60min': 'Sesión 1 hora',
    'preset90min': 'Sesión 1h30',
    'minutes': 'Minutos',
    'seconds': 'Segundos',
    'frequency': 'Frecuencia de anuncios',
    'slow': 'Lento (7s)',
    'normal': 'Normal (5s)',
    'fast': 'Rápido (3s)',
    'double': 'Doble',
    'triple': 'Triple',
    'skipRound': 'Saltar al siguiente round',
    'skipBlock': 'Saltar al siguiente bloque',
    'voiceProfile': 'Voz',
    'trainingComplete': '¡Entrenamiento completado!',
    'theme': 'Ambiente',
    'sport': 'Deporte',
    'exercise': 'Ejercicio',
    'backToTraining': 'Volver al entrenamiento',
    'noSavedWorkouts': 'No hay entrenamientos guardados',
    'deleteConfirm': '¿Eliminar este entrenamiento?',
    'saveCurrentWorkout': 'Guardar este entrenamiento',
    'createdOn:': 'Creado el',
    'newName': 'Nuevo nombre',
    'selectWorkout': 'Seleccionar entrenamiento'
  }
}

THEMES = {
  'muayThaiCamp': {
    'name': { 'fr': 'Camp Muay Thaï', 'en': 'Muay Thai Camp', 'es': 'Campo Muay Thai' },
    'colors': {
      'primary': '#dc2626',
      'secondary': '#fbbf24',
      'background': 'from-red-900 via-orange-900 to-yellow-900',
      'cardBg': 'rgba(153, 27, 27, 0.7)'
    }
  },
  'boxingGym': {
    'name': { 'fr': 'Salle de Boxe', 'en': 'Boxing Gym', 'es': 'Gimnasio de Boxeo' },
    'colors': {
      'primary': '#1e40af',
      'secondary': '#dc2626',
      'background': 'from-gray-900 via-blue-900 to-black',
      'cardBg': 'rgba(30, 58, 138, 0.7)'
    }
  },
  'okinawaDojo': {
    'name': { 'fr': 'Dojo d\'Okinawa', 'en': 'Okinawa Dojo', 'es': 'Dojo de Okinawa' },
    'colors': {
      'primary': '#78350f',
      'secondary': '#dc2626',
      'background': 'from-amber-900 via-stone-800 to-neutral-900',
      'cardBg': 'rgba(120, 53, 15, 0.7)'
    }
  }
}
